### ISSUE TITLE
builtins.ImportError: cannot import name 'prints_tb'

### ISSUE THREAD

**Issue by blackapex** [glennake/DirectFire_Converter#6]
Hi Glenn,

I installed all requirements and receive this error during a conversion from Watchguard to Fortigate:

  File "watchguard.py", line 7, in <module>
    from traceback_with_variables import prints_tb, LoggerAsFile
      ...skipped... 10 vars
builtins.ImportError: cannot import name 'prints_tb'

Would this be something small (I hope :) ?

Regards

**Comment by glennake** [comment]
Hi @blackapex,

What platform, OS and version of Python are you using?

Can you also provide pip3 freeze output?

Thanks

**Comment by mhsanein** [comment]
Hi Glenn,
same error i found and following PIP freeze output
appdirs==1.4.4
certifi==2020.12.5
chardet==4.0.0
colorama==0.4.3
distlib==0.3.1
filelock==3.0.12
idna==2.10
logger==1.4
pyfiglet==0.8.post1
regex==2020.11.13
requests==2.25.1
six==1.15.0
traceback-with-variables==2.0.1
Unidecode==1.1.2
urllib3==1.26.2
virtualenv==20.2.2

**Comment by blackapex** [comment]
I am sorry for the delay. Hereby the output:

$ pip3 freeze
colorama==0.4.3
et-xmlfile==1.0.1
jdcal==1.4.1
openpyxl==3.0.6
traceback-with-variables==2.0.1
Unidecode==1.1.2

**Comment by glennake** [comment]
Hi @blackapex @mhsanein,

Thanks for raising this, looks like it is due to an update to the dependancy traceback-with-variables.

I have updated the code so pull the latest and try again please?

Thanks,
Glenn
